name: Build arc42 PDF

on:
  push:
    branches:
      - master
    paths:
      - docs/arc42/**

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest   # Contenedor oficial con Pandoc + LaTeX

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependencias (mermaid-cli + pandoc-mermaid)
        run: |
          apt-get update && apt-get install -y nodejs npm python3-pip
          npm install -g @mermaid-js/mermaid-cli
          pip install pandoc-mermaid

      - name: Generar PDF
        run: |
          pandoc docs/arc42/arc42.md \
            --filter pandoc-mermaid \
            -o docs/arc42/arc42.pdf

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: arc42-pdf
          path: docs/arc42/arc42.pdf
