name: Build arc42 PDF

on:
  push:
    branches:
      [ "master" ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar md-to-pdf
        run: |
          npm install -g md-to-pdf

      - name: Generar PDF
        run: |
          md-to-pdf docs/arc42/arc42.md --basedir docs/arc42

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: arc42-pdf
          path: docs/arc42/arc42.pdf

