name: Build arc42 Formal PDF

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin

      - name: Instalar Mermaid CLI y filtro
        run: |
          npm install -g @mermaid-js/mermaid-cli
          pip3 install pandoc-mermaid-filter

      - name: Generar PDF formal con Pandoc + filtro
        run: |
          pandoc docs/arc42/arc42.md \
            --from markdown \
            --pdf-engine=xelatex \
            --filter pandoc-mermaid-filter \
            -V geometry:a4paper \
            -V mainfont="DejaVu Serif" \
            -V sansfont="DejaVu Sans" \
            -V monofont="DejaVu Sans Mono" \
            -V fontsize=11pt \
            -V linkcolor=blue \
            -o docs/arc42/arc42.pdf

      - name: Commit & Push PDF al repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/arc42/arc42.pdf
          git commit -m "chore(docs): update arc42.pdf [skip ci]" || echo "No changes to commit"
          git push
