name: Build arc42 PDF

on:
  push:
    branches:
      - master
    paths:
      - docs/arc42/**

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Instalar pandoc con acción oficial
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Setup Node (para mermaid-cli)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      # Setup Python (para pandoc-mermaid)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar filtro pandoc-mermaid
        run: pip install pandoc-mermaid

      # Generar PDF
      - name: Generar PDF con Pandoc
        run: |
          pandoc docs/arc42/arc42.md \
            --filter pandoc-mermaid \
            -o docs/arc42/arc42.pdf

      # Guardar PDF como artefacto
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: arc42-pdf
          path: docs/arc42/arc42.pdf
