name: Build arc42 PDF

on:
  push:
    branches:
      [ "master" ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Marp
        run: npm install -g @marp-team/marp-cli

      - name: Generar PDF con Marp
        run: |
          marp docs/arc42/arc42.md \
            --pdf \
            --allow-local-files \
            --output docs/arc42/arc42.pdf

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: arc42-pdf
          path: docs/arc42/arc42.pdf