name: Build and Push Flutter Web Frontend to Docker Hub

on:
  push:
    branches:
      [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter build web
        run: flutter build web
        working-directory: ./src/frontend

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          tags: gitzerohub/as_asistenciamovil:latest
